### PR TITLE
Add tenting to the bottom of all vias

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Closes [Fix VCC via under CR2032 battery](https://trello.com/c/4aSTalKE/5-fix-vcc-via-under-cr2032-battery)

### CODE REVIEW

**Comment by GeorgeHahn** [comment]
Apologies for sending a PR from my master branch

**Comment by GeorgeHahn** [comment]
Apologies for sending a PR from my master branch

**Comment by ps2** [comment]
Can you add updated gerbers for this?

**Comment by GeorgeHahn** [comment]
Gerbers added in 0b641f8

**Comment by ps2** [comment]
@GeorgeHahn Sounds like like just the BOM update is left here. I'll merge in when you let me know it's ready.

**Comment by GeorgeHahn** [comment]
Updated BOM with Digikey parts

**Pull request merged**
